name: CI github pages

on:
  push:
    branches:
      - main
    paths:
      - 'launch.txt'
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency: 
      group: "pages"
      cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove old output files
        run: |
          if [ -f index.html ]; then
            rm index.html;
          fi;
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          pip install pandas;
          pip install altair;
          pip install requests;
          
      - name: Create the index.html
        run: |
            URL_CONTENT="$(cat launch.txt | cut -d '|' -f 1)"; 
            echo "URL_CONTENT = $URL_CONTENT";
            # ---------------------------------------
            # Obtain data in JSON
            curl -H "Accept: application/json" -H "Content-Type: application/json" -X GET $URL_CONTENT > data.json;
            cat data.json > data.csv;
            json_str=$(cat data.json);
            echo "json_str = $json_str";
            # ---------------------------------------
            result="$(python '${{ github.workspace }}/main.py' $json_str)";
            echo "$result" > index.html;
            cat index.html
          
      - name: Commit and push changes
        run: |
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoOwnerEmail="j622amilah@gmail.com";
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git pull origin main;
          git checkout main;
          git branch --set-upstream-to origin/main;
          git merge main --ff-only;
          git add /home/runner/work/static_HTML/static_HTML/index.html;
          git diff-index --quiet HEAD || git commit -m "add files" --allow-empty;
          git push
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # location of the artifacts
          path: "./"
        

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
